services:
  - type: web
    name: joomla
    env: php
    buildCommand: |
      composer install --no-interaction --no-dev --prefer-dist
      cp configuration.php.render configuration.php
    startCommand: vendor/bin/heroku-php-apache2
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: joomla-db
          property: host
      - key: DB_USER
        fromDatabase:
          name: joomla-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: joomla-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: joomla-db
          property: database
buildCommand: |
  docker-php-ext-install pdo_pgsql
  composer install --no-interaction --no-dev --prefer-dist
  cp configuration.php.render configuration.php
